name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true
            python-version: 3.11
      - name: Install tox with patched tox-gh
        run: uv tool install tox --with tox-uv --with tox-gh
      - name: Run lint
        run: tox -e lint

  test:
    name: test py${{ matrix.py }}-django${{ matrix.django }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        django: ["50", "51", "60"]
        os: [ubuntu-latest]
        exclude:
          - py: "3.10"
            django: "60"
          - py: "3.11"
            django: "60"
      fail-fast: false
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: dif_test_pass
          POSTGRES_DB: dif_test_db
          POSTGRES_USER: dif_test_user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      POSTGRES_DB: dif_test_db
      POSTGRES_USER: dif_test_user
      POSTGRES_PASSWORD: dif_test_pass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install tox
        run: uv tool install --python-preference only-managed --python ${{ matrix.py }} tox --with tox-uv --with tox-gh
      - name: Install Python
        run: uv python install --python-preference only-managed ${{ matrix.py }}
      - name: Setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false -e py$(echo "${{ matrix.py }}" | tr -d '.')-django${{ matrix.django }}
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.py }}
      - name: Run test suite
        run: tox run --skip-pkg-install -e py$(echo "${{ matrix.py }}" | tr -d '.')-django${{ matrix.django }}
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.py }}

  coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: dif_test_pass
          POSTGRES_DB: dif_test_db
          POSTGRES_USER: dif_test_user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      POSTGRES_DB: dif_test_db
      POSTGRES_USER: dif_test_user
      POSTGRES_PASSWORD: dif_test_pass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.11"
      - name: Install tox with patched tox-gh
        run: uv tool install tox --with tox-uv --with tox-gh
      - name: Run coverage
        run: tox -e coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
